# Configuration for profile docker.
spring:
  profiles: k8s
  profiles.include:
    - secretsharestore-minio
    - entitystore-postgres
    - cache-redis

logging:
  level:
    ROOT: INFO
    io.carbynestack: ${LOG_LEVEL:INFO}
    org.springframework: INFO
